### ISSUE TITLE
Repository way too big

### ISSUE THREAD

**Issue by TimZaman** [D-K-E/ptm-viewer#2]
This repository in its entirely is hundreds of megabytes, and I stopped checking it in.

I don't think there's a reason for this repository to be more then a few kb. Probably you want to clean up the git history of the repo in order to make it a more humane size.

**Comment by D-K-E** [comment]
Thanks for the call. I'll do that when I have a little time.
I am changing most of the interface now.
I decided to delegate all graphical rendering to opengl and the front end to PySide2.   
Once that is done, I'll delete the history of the repository, since it would be more or less meaningless to have it.

**Comment by D-K-E** [comment]
@TimZaman cleaned up the repo history as promised if you feel like checking the project out. It still misses quite a bit of features, but rendering is now done in OpenGL, so it should be quite fast.
