### ISSUE TITLE
problem installing ptm-viewer

### ISSUE THREAD

**Issue by FrancescaPimpinelli** [D-K-E/ptm-viewer#4]
Hello!
I'm trying to install ptm-viewer, I followed all the info about it but it give me this error when I try to run python app.py:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from core import setUpHandler
ImportError: cannot import name 'setUpHandler' from 'core' (/home/pimpi/ptm-viewer/main/core.py)

Could you help me?

**Comment by D-K-E** [comment]
Hi,
I have stated in #3 the commit you can go back to for trying the application.
You can checkout the commit "17befa86f6db2bbf3" in branch dev.
If you have the necessary libraries you can then launch the from the
top folder by `python main/app.py`.
But it is SLOW because all the computations are done in numpy. I am working on an opengl backend, which should speed up things quite a bit.
If you just one to explore the code though I suggest you to revert back to that commit.

**Comment by D-K-E** [comment]
As per our communication, the structure of the repo is too irrelevant now to respond to this issue thus I am closing it.
